<a href="https://colab.research.google.com/github/kimsihyun0129/ArtificialIntelligence/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%8B%A4%EB%A3%A8%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터 다루기

## numpy

### 넘파이의 array() 메소드를 사용하여 배열을 생성

In [ ]:
import numpy as np  # numpy 패키지를 np라는 이름으로 불러옴

ar1 = np.array([1,2,3,4,5])
ar2 = np.array([[1,2,3],[4,5,6]])
print(ar1)
print(ar2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### 난수를 이용한 2차원 배열 객체 생성

In [ ]:
ar3 = np.random.randn(3) # 3 크기의 1차원 배열 생성(난수 발생)
ar4 = np.random.randn(2,3) # 2*3 크기의 2차원 배열 생성(난수 발생)
print(ar3)
print(ar4)

[ 0.00732598 -1.33791364  1.23106667]
[[ 1.77504096  1.1829893  -0.41408016]
 [ 0.59720279 -1.99371591  0.55029032]]


### 원소를 0 또는 1로 초기화

In [ ]:
ar5 = np.zeros(5)
ar6 = np.ones((2,3))
print(ar5)
print(ar6)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


### arange()와 reshape() 메소드 이용

In [ ]:
ar7 = np.arange(20,200,10) # 20부터 200-1까지 10씩 증가
ar8 = ar7.reshape(3,6) # 3*6배열로 재배치
print(ar7)
print(ar8)

[ 20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180 190]
[[ 20  30  40  50  60  70]
 [ 80  90 100 110 120 130]
 [140 150 160 170 180 190]]


### 배열 다루기

In [ ]:
ar1 = np.arange(1,21,1)
print(ar1)
print(ar1[1])

ar2 = ar1.reshape(2,10)
print(ar2)
ar2[1][1] = 100
print(ar2[1][0], ar2[1][1], ar2[1][2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
2
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
11 100 13


### 배열의 산술 연산

In [ ]:
ar1 = np.arange(1,11,1)
ar2 = ar1+3
ar3 = ar1*2

print(ar1)
print(ar2,"\n",ar3)

[ 1  2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10 11 12 13] 
 [ 2  4  6  8 10 12 14 16 18 20]


### 배열의 통계 메소드 사용

In [ ]:
ar1 = np.array([[5,7,9],[-7,-6,19],[6,9,11]])
print(ar1)
print(ar1.sum())  # 배열 원소의 합계
print(ar1.mean()) # 배열 원소의 평균
print(ar1.max())  # 배열 원소 중 가장 큰 값
print(ar1.min())  # 배열 원소 중 가장 작은 값
print(ar1.max(axis=0))  # 배열의 각 열의 원소 중 가장 큰 값을 구함
print(ar1.max(axis=1))  # 배열의 각 행의 원소 중 가장 큰 값을 구함

[[ 5  7  9]
 [-7 -6 19]
 [ 6  9 11]]
53
5.888888888888889
19
-7
[ 6  9 19]
[ 9 19 11]


### 심화 조건식을 사용한 연산

In [ ]:
ar1 = np.array([[5,7,9],[-7,-6,19],[6,9,11]])
print(ar1 > 0)  # ar1의 각 원소가 0보다 큰지 판단한 결과를 출력

m_count = (ar1 < 0).sum() # 원소 중 음수가 몇 개인지 계산(false의 개수)
print(m_count)

ar2 = np.where(ar1 < 0, 0, ar1) # ar1의 원소가 0보다 작으면 0으로 변경, 그렇지 않으면 ar1의 값으로 대
print(ar2)

[[ True  True  True]
 [False False  True]
 [ True  True  True]]
2
[[ 5  7  9]
 [ 0  0 19]
 [ 6  9 11]]


## Pandas

### 시리즈(series) 객체 생성하기

In [ ]:
import pandas as pd # 판다스 패키지를 불러와서 pd라는 이름으로 사용

sr1 = pd.Series([10,20,30,40,50])  # 리스트를 시리즈 객체로 생성
print(sr1)

0    10
1    20
2    30
3    40
4    50
dtype: int64


### 시리즈 객체의 값과 인덱스 확인

In [ ]:
sr1 = pd.Series([10,30,20,40,50])

print(sr1.values) # 시리즈 sr1의 값 출력
print(sr1.index)  # 시리즈 sr1의 인덱스 출력(처음값, 마지막값, 증가값)
print(sr1[2])     # 인덱스 2에 해당하는 값 출력

[10 30 20 40 50]
RangeIndex(start=0, stop=5, step=1)
20


### 시리즈(series) 객체의 인덱스 생성

In [ ]:
sr1 = pd.Series([10,30,20,40,50], index=['a','b','c','d','e'])

print(sr1[1])     # 숫자 인덱스
print(sr1['b'])   # 문자 인덱스

30
30


<ipython-input-15-8899fa93f6eb>:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(sr1[1])


### 원소 선택

In [ ]:
sr1 = pd.Series([10,30,20,40,50], index=['a','b','c','d','e'])

print(sr1[[1,2]])
print(sr1[['a','c']])
print(sr1[1:4])
print(sr1['b':'d'])

b    30
c    20
dtype: int64
a    10
c    20
dtype: int64
b    30
c    20
d    40
dtype: int64
b    30
c    20
d    40
dtype: int64


<ipython-input-20-6dc130f8951c>:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(sr1[[1,2]])


### 데이터 프레임 객체 생성하기

In [ ]:
df1 = pd.DataFrame([[10,20,30],[40,50,60]])
print(df1)

    0   1   2
0  10  20  30
1  40  50  60


### 딕셔너리를 이용한 데이터 프레임 생성

In [ ]:
dic1 = {'fruit':['사과','배','감','귤','바나나'],'price':[100,200,150,50,200],'qty':[10,25,30,20,15]}
df1 = pd.DataFrame(dic1) # 딕셔너리를 데이터프레임으로 생성
df1

fruit  price  qty
0    사과    100   10
1     배    200   25
2     감    150   30
3     귤     50   20
4   바나나    200   15

### 데이터 프레임 객체의 인덱스(행)/열이름 설정하기

In [ ]:
df1 = pd.DataFrame(dic1, index=['a','b','c','d','e'])
df1

fruit  price  qty
a    사과    100   10
b     배    200   25
c     감    150   30
d     귤     50   20
e   바나나    200   15

### 데이터 프레임 객체의 인덱스(행)/열이름 설정하기 2

In [ ]:
df1.rename(columns={'fruit':'과일','price':'가격','qty':'수량'}, inplace=True)
df1.rename(index={'a':'01','b':'02','c':'03','d':'04','e':'05'}, inplace=True)
df1

과일   가격  수량
01   사과  100  10
02    배  200  25
03    감  150  30
04    귤   50  20
05  바나나  200  15

## 코랩에서 데이터 읽어오기

In [ ]:
# Colab에 구글 드라이브 마운트
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/df_sample.csv')  # 구글 드라이브에 업로드한 파일 읽기
df

학번  중간  기말  리포트  퀴즈
0  S01  10  39   15   5
1  S02  11  38   16   6
2  S03  12  37   17   7
3  S04  13  36   18   8
4  S05  14  35   19   9
5  S06  15  36   20  10
6  S07  16  37   21  11
7  S08  17  32   22  12
8  S09  18  31   23  13
9  S10  19  30   24  14

## 데이터 전처리

### 파생변수 생성

In [ ]:
df["합계"] = df["중간"] + df["기말"]  # 중간과 기말 점수를 더해 '합계'열로 생성
x = ["1반","1반","1반","2반","2반","2반","3반","3반","3반","3반"] # 리스트 정의

df["cls"] = x

df

학번  중간  기말  리포트  퀴즈  합계 cls
0  S01  10  39   15   5  49  1반
1  S02  11  38   16   6  49  1반
2  S03  12  37   17   7  49  1반
3  S04  13  36   18   8  49  2반
4  S05  14  35   19   9  49  2반
5  S06  15  36   20  10  51  2반
6  S07  16  37   21  11  53  3반
7  S08  17  32   22  12  49  3반
8  S09  18  31   23  13  49  3반
9  S10  19  30   24  14  49  3반

### 표준화

In [ ]:
mid_avg = np.mean(df["중간"]) # 중간시험 점수 평균
mid_std = np.std(df["중간"])  # 중간시험 점수 표준편차

# 중간시험 Z-score 열 생성
df["중간_Z점수"] = (df["중간"]-mid_avg)/mid_std

df.head()

학번  중간  기말  리포트  퀴즈  합계 cls    중간_Z점수
0  S01  10  39   15   5  49  1반 -1.566699
1  S02  11  38   16   6  49  1반 -1.218544
2  S03  12  37   17   7  49  1반 -0.870388
3  S04  13  36   18   8  49  2반 -0.522233
4  S05  14  35   19   9  49  2반 -0.174078

### 정규화

In [ ]:
fin_min = np.min(df["기말"])  # 기말 점수 최소값
fin_max = np.max(df["기말"])  # 기말 점수 최대값

# 기말 점수 정규화
df["기말_정규화"] = (df["기말"]-fin_min)/(fin_max-fin_min)

df.head()

학번  중간  기말  리포트  퀴즈  합계 cls    중간_Z점수    기말_정규화
0  S01  10  39   15   5  49  1반 -1.566699  1.000000
1  S02  11  38   16   6  49  1반 -1.218544  0.888889
2  S03  12  37   17   7  49  1반 -0.870388  0.777778
3  S04  13  36   18   8  49  2반 -0.522233  0.666667
4  S05  14  35   19   9  49  2반 -0.174078  0.555556

## 데이터 요약

### 집계 함수 적용

In [ ]:
df_cls_grp = df.groupby(df['cls'])
df_cls_grp.mean(numeric_only=True) # 그룹별 열의 평균

중간         기말   리포트    퀴즈         합계
cls                                        
1반   11.0  38.000000  16.0   6.0  49.000000
2반   14.0  35.666667  19.0   9.0  49.666667
3반   17.5  32.500000  22.5  12.5  50.000000

In [ ]:
df['중간'].groupby(df['cls']).count() # 그룹별 열의 개수

cls
1반    3
2반    3
3반    4
Name: 중간, dtype: int64

### 행 또는 열에 지정한 함수 적용

In [ ]:
df["퀴즈"].apply(np.sqrt)

0    2.236068
1    2.449490
2    2.645751
3    2.828427
4    3.000000
5    3.162278
6    3.316625
7    3.464102
8    3.605551
9    3.741657
Name: 퀴즈, dtype: float64

### 결측값 식별

In [ ]:
x = [14,15,13,14,None,None,19,11,12,18]
df["토론"] = x  # 결측값이 있는 컬럼 "토론" 추가

df.info() # 데이터 프레임 요약정보 출력 : NaN의 개수를 알 수 있음

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   학번      10 non-null     object 
 1   중간      10 non-null     int64  
 2   기말      10 non-null     int64  
 3   리포트     10 non-null     int64  
 4   퀴즈      10 non-null     int64  
 5   합계      10 non-null     int64  
 6   cls     10 non-null     object 
 7   토론      8 non-null      float64
dtypes: float64(1), int64(5), object(2)
memory usage: 772.0+ bytes


### 결측값 대치

In [ ]:
# 완전분석법(결측값이 있는 행 제거)
df_new = df.dropna(axis=0)  # 결측값이 있는 행 전체 제거 (axis=1이면 열을 제거)
df_new = df["토론"].dropna() # "토론"열에서 결측값 제거
df_new

0    14.0
1    15.0
2    13.0
3    14.0
6    19.0
7    11.0
8    12.0
9    18.0
Name: 토론, dtype: float64

In [ ]:
# 평균대치법(결측값을 평균값으로 대체)
d_mean = df["토론"].mean()
df["토론"].fillna(d_mean, inplace=True) # 결측값을 평균값으로 대치
df

### 이상값(outlier) 처리

In [ ]:
df_10R = df["기말"].quantile(0.25)  # 1사분위수
df_3QR = df["기말"].quantile(0.75)  # 3사분위수
df_1QR = df_3QR - df_10R            # 사분위 범위
print(df_10R)
print(df_3QR)
print(df_1QR)

32.75
37.0
4.25
