<a href="https://colab.research.google.com/github/kimsihyun0129/ArtificialIntelligence/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_%EB%B0%8F_%ED%95%99%EC%8A%B5_%EA%B3%BC%EC%A0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터 분석 및 학습 과정

## 1. 필요 패키지 임포트(import)

In [ ]:
import numpy as np  # 넘파이 패키지 임포트
import pandas as pd # 판다스 패키지 임포트
import sklearn      # 싸이킷런 패키지 임포트

# 의사결정 나무 분류 모델을 위한 패키지 임포트
from sklearn.tree import DecisionTreeClassifier

# 학습 및 테스트 데이터셋 분리를 위한 패키지 임포트
from sklearn.model_selection import train_test_split

## 2. 데이터 수집/불러오기

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")

## 3. 데이터 탐색

In [ ]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df.shape # 데이터프레임의 열과 행의 수를 출력

(150, 5)

In [ ]:
df.info() # 데이터프레임의 요약정보 출력

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
df.describe() # 데이터프레임의 기술통계 보여주기

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

## 4. 데이터 전처리

In [ ]:
# 텍스트로 되어 있는 species 컬럼의 데이터를 0,1,2로 변환한다.
df['species'].replace({'setosa':0,'versicolor':1,'virginica':2},inplace=True)
df

<ipython-input-10-838039348f70>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['species'].replace({'setosa':0,'versicolor':1,'virginica':2},inplace=True)
<ipython-input-10-838039348f70>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['species'].replace({'setosa':0,'versicolor':1,'virginica'

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[150 rows x 5 columns]

## 5. 학습 데이터셋 준비

In [ ]:
# 분석 데이터셋 준비
# X는 독립변수(설명변수), y는 종속변수(목표변수)
X = df[["sepal_length","sepal_width","petal_length","petal_width"]]
y = df["species"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=11)

In [ ]:
print(X_train.shape)  # 학습 데이터(독립변수)
print(X_test.shape)   # 테스트 데이터(독립변수)
print(y_train.shape)  # 학습 데이터(종속변수)
print(y_test.shape)   # 테스트 데이터(종속변수)

(120, 4)
(30, 4)
(120,)
(30,)


## 6. 학습 수행

In [ ]:
# DecisionTreeClassifier 객체 생성
dt = DecisionTreeClassifier(random_state=11)
dt.fit(X_train, y_train)  # 학습 수행

DecisionTreeClassifier(random_state=11)

In [ ]:
# 학습이 완료된 dt 객체에서 테스트 데이터셋으로 예측 수행
pred = dt.predict(X_test)

In [ ]:
print(y_test.values)
print(pred)

[2 2 2 1 2 0 1 0 0 1 2 1 1 2 2 0 2 1 2 2 1 0 0 1 0 0 2 1 0 1]
[2 2 1 1 2 0 1 0 0 1 1 1 1 2 2 0 2 1 2 2 1 0 0 1 0 0 2 1 0 1]


## 7. 성능평가 및 시각화

In [ ]:
# 모델 성능 - 정확도 측정
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, pred)
print(acc)

0.9333333333333333


### 학습 모델의 성능평가

In [ ]:
# 1. 오차 행렬(Confusion Matrix, 혼동 행렬)
# 모델 성능 - 오차 행렬
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, pred)

array([[ 9,  0,  0],
       [ 0, 10,  0],
       [ 0,  2,  9]])

In [ ]:
# 2. 모델 평가 지표
# 모델 성능 평가 - 평가 지표 계산
from sklearn.metrics import classification_report
rpt = classification_report(y_test, pred)
print(rpt)

# 1 정확도
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, pred)
print(acc)

# 2 정밀도
from sklearn.metrics import precision_score
pre = precision_score(y_test, pred, average=None)
print(pre)

# 3 재현율
from sklearn.metrics import recall_score
rec = recall_score(y_test, pred, average=None)
print(rec)

# 4 F1 Score
from sklearn.metrics import f1_score
f1 = f1_score(y_test, pred, average=None)
print(f1)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.83      1.00      0.91        10
           2       1.00      0.82      0.90        11

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.94      0.93      0.93        30

0.9333333333333333
[1.         0.83333333 1.        ]
[1.         1.         0.81818182]
[1.         0.90909091 0.9       ]
